name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    # monthly
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Publish to GitHub Container Registry
        env:
          REGISTRY: ghcr.io/appscode
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          cd alpine; make release; cd ..
          cd debian; make release; cd ..
          cd distroless; make release; cd ..
          cd opensuse-leap; make release; cd ..
          cd ubuntu; make release; cd ..
